# Generated by Django 4.2.5 on 2023-09-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=150)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('returnTime', models.DateTimeField(null=True)),
                ('photoName', models.CharField(default='bk1.jpg', max_length=50)),
                ('borrowed_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
        ),
    ]
