# Generated by Django 4.2.5 on 2023-09-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photoName',
            field=models.CharField(default='1.jpg', max_length=50),
        ),
    ]
